ProxyRequests Off
ProxyPreserveHost Off
ProxyPassInterpolateEnv On
PassEnv PR2HUB_PROXY_URL

ProxyPass "/pr2hub/" "${PR2HUB_PROXY_URL}/" interpolate connectiontimeout=3 timeout=10 retry=0
ProxyPassReverse "/pr2hub/" "${PR2HUB_PROXY_URL}/" interpolate
